{
    "Information": {
        "Category": [
            {
                "url": "https://cwe.mitre.org/data/definitions/668.html", 
                "id": "CWE-668", 
                "title": "Exposure of Resource to Wrong Sphere"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/199.html", 
                "id": "CWE-199", 
                "title": "Information Management Errors"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/717.html", 
                "id": "CWE-717", 
                "title": "OWASP Top Ten 2007 Category A6 - Information Leakage and Improper Error Handling"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/840.html", 
                "id": "CWE-840", 
                "title": "Business Logic Errors"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/963.html", 
                "id": "CWE-963", 
                "title": "SFP Secondary Cluster: Exposed Data"
            }
        ], 
        "CAPEC": [
            {
                "url": "https://capec.mitre.org/data/definitions/13.html", 
                "id": 13
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/169.html", 
                "id": 169
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/22.html", 
                "id": 22
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/472.html", 
                "id": 472
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/59.html", 
                "id": 59
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/60.html", 
                "id": 60
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/79.html", 
                "id": 79
            }
        ], 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2011-1015", 
                "published": "2011-05-09T18:55:01.677-04:00", 
                "id": "CVE-2011-1015", 
                "modified": "2013-05-14T23:16:47.750-04:00", 
                "summary": "The is_cgi method in CGIHTTPServer.py in the CGIHTTPServer module in Python 2.5, 2.6, and 3.0 allows remote attackers to read script source code via an HTTP GET request that lacks a / (slash) character at the beginning of the URI."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/200.html", 
                "id": "CWE-200", 
                "title": "Information Exposure"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:python:python:3.0"
            }, 
            {
                "id": "cpe:/a:python:python:2.5"
            }, 
            {
                "id": "cpe:/a:python:python:2.6"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.57398", 
                "id": 57398
            }
        ], 
        "IAVM": [
            {
                "Disa key": "V0031252", 
                "id": "2012-A-0020", 
                "title": "Multiple Vulnerabilities in VMware ESX 4.1 and ESXi 4.1"
            }
        ], 
        "BID": [
            {
                "url": "http://www.securityfocus.com/bid/46541", 
                "id": 46541
            }
        ], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://svn.python.org/view?view=revision&revision=71303", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://openwall.com/lists/oss-security/2011/02/24/10", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://openwall.com/lists/oss-security/2011/02/23/27", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://hg.python.org/cpython/rev/c6c4398293bd/", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://bugs.python.org/issue2254", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://www.securityfocus.com/bid/46541", 
                    "vendor": "BID"
                }, 
                {
                    "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2011:096", 
                    "vendor": "MANDRIVA"
                }, 
                {
                    "url": "http://securitytracker.com/id?1025489", 
                    "vendor": "SECTRACK"
                }, 
                {
                    "url": "http://secunia.com/advisories/51040", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/51024", 
                    "vendor": "SECUNIA"
                }, 
                {
                    "url": "http://secunia.com/advisories/50858", 
                    "vendor": "SECUNIA"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "2.9", 
                    "access complexity": "low", 
                    "confidentiality impact": "partial", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "5.0", 
                    "integrity impact": "none", 
                    "availability impact": "none", 
                    "access vector": "network"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2011-1015"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:17830", 
                "title": "USN-1613-1 -- python2.5 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:17830"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:23229", 
                "title": "ELSA-2011:0492: python security update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:23229"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28060", 
                "title": "DEPRECATED: ELSA-2011-0492 -- python security update (moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28060"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:28032", 
                "title": "DEPRECATED: ELSA-2011-0554 -- python security, bug fix, and enhancement update (moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:28032"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:23473", 
                "title": "ELSA-2011:0554: python security, bug fix, and enhancement update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:23473"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18020", 
                "title": "USN-1613-2 -- python2.4 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18020"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21923", 
                "title": "RHSA-2011:0492: python security update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21923"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21626", 
                "title": "RHSA-2011:0554: python security, bug fix, and enhancement update (Moderate)", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21626"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:20416", 
                "title": "VMware ESXi and ESX updates to third party library and ESX Service Console", 
                "class": "vulnerability", 
                "id": "oval:org.mitre.oval:def:20416"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18043", 
                "title": "USN-1596-1 -- python2.6 vulnerabilities", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18043"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "CentOS Update for python CESA-2011:0491 centos4 i386", 
                "file": "gb_CESA-2011_0491_python_centos4_i386.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "880556"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0491 centos4 x86_64", 
                "file": "gb_CESA-2011_0491_python_centos4_x86_64.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "881427"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0492 centos5 i386", 
                "file": "gb_CESA-2011_0492_python_centos5_i386.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "880500"
            }, 
            {
                "name": "CentOS Update for python CESA-2011:0492 centos5 x86_64", 
                "file": "gb_CESA-2011_0492_python_centos5_x86_64.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "881282"
            }, 
            {
                "name": "Mandriva Update for python MDVSA-2011:096 (python)", 
                "file": "gb_mandriva_MDVSA_2011_096.nasl", 
                "family": "Mandrake Local Security Checks", 
                "id": "831403"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0491-01", 
                "file": "gb_RHSA-2011_0491-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870430"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0492-01", 
                "file": "gb_RHSA-2011_0492-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870428"
            }, 
            {
                "name": "RedHat Update for python RHSA-2011:0554-01", 
                "file": "gb_RHSA-2011_0554-01_python.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "870597"
            }, 
            {
                "name": "Ubuntu Update for python2.6 USN-1596-1", 
                "file": "gb_ubuntu_USN_1596_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841178"
            }, 
            {
                "name": "Ubuntu Update for python2.5 USN-1613-1", 
                "file": "gb_ubuntu_USN_1613_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841195"
            }, 
            {
                "name": "Ubuntu Update for python2.4 USN-1613-2", 
                "file": "gb_ubuntu_USN_1613_2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841194"
            }, 
            {
                "name": "VMSA-2012-0001 VMware ESXi and ESX updates to third party library and ESX Service Console", 
                "file": "gb_VMSA-2012-0001.nasl", 
                "family": "VMware Local Security Checks", 
                "id": "103448"
            }
        ], 
        "Nessus": [
            {
                "name": "CentOS 4 : python (CESA-2011:0491)", 
                "file": "centos_RHSA-2011-0491.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "53814"
            }, 
            {
                "name": "CentOS 5 : python (CESA-2011:0492)", 
                "file": "centos_RHSA-2011-0492.nasl", 
                "family": "CentOS Local Security Checks", 
                "id": "53815"
            }, 
            {
                "name": "GLSA-201401-04 : Python: Multiple vulnerabilities", 
                "file": "gentoo_GLSA-201401-04.nasl", 
                "family": "Gentoo Local Security Checks", 
                "id": "71811"
            }, 
            {
                "name": "Mandriva Linux Security Advisory : python (MDVSA-2011:096)", 
                "file": "mandriva_MDVSA-2011-096.nasl", 
                "family": "Mandriva Local Security Checks", 
                "id": "54611"
            }, 
            {
                "name": "Oracle Linux 4 : python (ELSA-2011-0491)", 
                "file": "oraclelinux_ELSA-2011-0491.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "68270"
            }, 
            {
                "name": "Oracle Linux 5 : python (ELSA-2011-0492)", 
                "file": "oraclelinux_ELSA-2011-0492.nasl", 
                "family": "Oracle Linux Local Security Checks", 
                "id": "68271"
            }, 
            {
                "name": "RHEL 4 : python (RHSA-2011:0491)", 
                "file": "redhat-RHSA-2011-0491.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "53820"
            }, 
            {
                "name": "RHEL 5 : python (RHSA-2011:0492)", 
                "file": "redhat-RHSA-2011-0492.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "53821"
            }, 
            {
                "name": "RHEL 6 : python (RHSA-2011:0554)", 
                "file": "redhat-RHSA-2011-0554.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "54592"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL4.x, SL5.x i386/x86_64", 
                "file": "sl_20110505_python_on_SL4_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "61033"
            }, 
            {
                "name": "Scientific Linux Security Update : python on SL6.x i386/x86_64", 
                "file": "sl_20110519_python_on_SL6_x.nasl", 
                "family": "Scientific Linux Local Security Checks", 
                "id": "61046"
            }, 
            {
                "name": "SuSE 11.1 Security Update : libpython2_6-1_0, libpython2_6-1_0-32bit, libpython2_6-1_0-x86, python, etc (SAT Patch Number 6310)", 
                "file": "suse_11_python-randomisation-update-120516.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "64220"
            }, 
            {
                "name": "SuSE 11.1 Security Update : libpython2_6-1_0, libpython2_6-1_0-32bit, libpython2_6-1_0-x86, python, etc (SAT Patch Number 6310)", 
                "file": "suse_11_python-randomisation-update-120517.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "64221"
            }, 
            {
                "name": "SuSE 10 Security Update : Python (ZYPP Patch Number 8080)", 
                "file": "suse_python-8080.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "58891"
            }, 
            {
                "name": "Ubuntu 10.04 LTS / 11.04 / 11.10 : python2.6 vulnerabilities (USN-1596-1)", 
                "file": "ubuntu_USN-1596-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62436"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.5 vulnerabilities (USN-1613-1)", 
                "file": "ubuntu_USN-1613-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62619"
            }, 
            {
                "name": "Ubuntu 8.04 LTS : python2.4 vulnerabilities (USN-1613-2)", 
                "file": "ubuntu_USN-1613-2.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "62620"
            }, 
            {
                "name": "VMSA-2012-0001 : VMware ESXi and ESX updates to third-party library and ESX Service Console", 
                "file": "vmware_VMSA-2012-0001.nasl", 
                "family": "VMware ESX Local Security Checks", 
                "id": "57749"
            }, 
            {
                "name": "VMware ESX / ESXi Service Console and Third-Party Libraries Multiple Vulnerabilities (VMSA-2012-0001) (remote check)", 
                "file": "vmware_VMSA-2012-0001_remote.nasl", 
                "family": "Misc.", 
                "id": "89105"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [
            {
                "url": "http://www.mandriva.com/security/advisories?name=MDVSA-2011:096", 
                "id": "MDVSA-2011:096"
            }
        ], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [], 
        "Redhat": [
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110491", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0491.html", 
                    "id": "RHSA-2011:0491", 
                    "title": "RHSA-2011:0491: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=531697", 
                    "title": "CVE-2009-3720 expat: buffer over-read and crash on XML with malformed UTF-8 sequences", 
                    "id": "531697", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=590690", 
                    "title": "CVE-2010-1634 python: audioop: incorrect integer overflow checks", 
                    "id": "590690", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=598197", 
                    "title": "CVE-2010-2089 Python: Memory corruption in audioop module", 
                    "id": "598197", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0491"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110492", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0492.html", 
                    "id": "RHSA-2011:0492", 
                    "title": "RHSA-2011:0492: python security update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=531697", 
                    "title": "CVE-2009-3720 expat: buffer over-read and crash on XML with malformed UTF-8 sequences", 
                    "id": "531697", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-05", 
                    "associated redhat": "RHSA-2011:0492"
                }
            }, 
            {
                "Redhat": {
                    "oval": "oval:com.redhat.rhsa:def:20110554", 
                    "url": "https://rhn.redhat.com/errata/RHSA-2011-0554.html", 
                    "id": "RHSA-2011:0554", 
                    "title": "RHSA-2011:0554: python security, bug fix, and enhancement update (Moderate)"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=603073", 
                    "title": "python >>> help() >>> modules command traceback when used without DISPLAY", 
                    "id": "603073", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=614680", 
                    "title": "Try to print repr() when a fatal garbage collection assertion fails", 
                    "id": "614680", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=625393", 
                    "title": "adjust test_commands unit test to the updated output of the ls command", 
                    "id": "625393", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=625395", 
                    "title": "include the tests/data directory in the python-test rpm", 
                    "id": "625395", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=626756", 
                    "title": "test_dbm fails on ppc64 & s390x", 
                    "id": "626756", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=627301", 
                    "title": "Rebase python from 2.6.5 to 2.6.6 in RHEL 6.1", 
                    "id": "627301", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=632200", 
                    "title": "CVE-2010-3493 Python: SMTP proxy RFC 2821 module DoS (uncaught exception) (Issue #9129)", 
                    "id": "632200", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=634944", 
                    "title": "rpmlint errors and warnings", 
                    "id": "634944", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=639392", 
                    "title": "Generating python backtrace with \"py-bt\" fails with a traceback", 
                    "id": "639392", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=649274", 
                    "title": "Infinite recursion in urllib2 on basicauth failure", 
                    "id": "649274", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=650588", 
                    "title": "subprocess fails in select when descriptors are large (rhel6)", 
                    "id": "650588", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=669847", 
                    "title": "urllib2's AbstractBasicAuthHandler is limited to 6 requests", 
                    "id": "669847", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=680094", 
                    "title": "CVE-2011-1015 python (CGIHTTPServer): CGI script source code disclosure", 
                    "id": "680094", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=684991", 
                    "title": "python update causes rhythmbox to crash", 
                    "id": "684991", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690315", 
                    "title": "python occasionally fails to build on machines with more than one core", 
                    "id": "690315", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }, 
            {
                "bugzilla": {
                    "url": "https://bugzilla.redhat.com/show_bug.cgi?id=690560", 
                    "title": "CVE-2011-1521 python (urllib, urllib2): Improper management of ftp:// and file:// URL schemes (Issue #11662)", 
                    "id": "690560", 
                    "issue date": "2011-05-19", 
                    "associated redhat": "RHSA-2011:0554"
                }
            }
        ], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [
            {
                "url": "http://www.ubuntu.com/usn/USN-1596-1", 
                "id": "USN-1596-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-1", 
                "id": "USN-1613-1"
            }, 
            {
                "url": "http://www.ubuntu.com/usn/USN-1613-2", 
                "id": "USN-1613-2"
            }
        ], 
        "Debian": [], 
        "Vmware": []
    }
}