{
    "Information": {
        "Category": null, 
        "CAPEC": null, 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2013-2132", 
                "published": "2013-08-15T13:55:24.500-04:00", 
                "id": "CVE-2013-2132", 
                "modified": "2013-10-07T15:35:50.130-04:00", 
                "summary": "bson/_cbsonmodule.c in the mongo-python-driver (aka. pymongo) before 2.5.2, as used in MongoDB, allows context-dependent attackers to cause a denial of service (NULL pointer dereference and crash) via vectors related to decoding of an \"invalid DBRef.\""
            }
        ], 
        "CWE": null, 
        "CPE": [
            {
                "id": "cpe:/a:mongodb:mongodb:2.2.0"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:2.4.4"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:2.0.0"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:1.8.0"
            }, 
            {
                "id": "cpe:/o:canonical:ubuntu_linux:12.04:-:lts"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:2.4.1"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:2.4.3"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:2.4.5"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:2.4.2"
            }, 
            {
                "id": "cpe:/o:canonical:ubuntu_linux:13.04"
            }, 
            {
                "id": "cpe:/o:novell:opensuse:12.3"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:1.4.0"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:1.2.0"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:2.4.0"
            }, 
            {
                "id": "cpe:/o:canonical:ubuntu_linux:12.10"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:2.5.1"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:2.5.0"
            }, 
            {
                "id": "cpe:/a:mongodb:mongodb:1.6.0"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.64670", 
                "id": 64670
            }
        ], 
        "IAVM": [], 
        "BID": [
            {
                "url": "http://www.securityfocus.com/bid/60252", 
                "id": 60252
            }
        ], 
        "OSVDB": [
            {
                "url": "http://www.osvdb.org/93804", 
                "id": 93804
            }
        ], 
        "Other": {
            "References": [
                {
                    "url": "https://github.com/mongodb/mongo-python-driver/commit/a060c15ef87e0f0e72974c7c0e57fe811bbd06a2", 
                    "vendor": "MISC"
                }, 
                {
                    "url": "https://jira.mongodb.org/browse/PYTHON-532", 
                    "vendor": "MISC"
                }, 
                {
                    "url": "http://www.securityfocus.com/bid/60252", 
                    "vendor": "BID"
                }, 
                {
                    "url": "http://www.osvdb.org/93804", 
                    "vendor": "OSVDB"
                }, 
                {
                    "url": "http://www.debian.org/security/2013/dsa-2705", 
                    "vendor": "DEBIAN"
                }, 
                {
                    "url": "http://ubuntu.com/usn/usn-1897-1", 
                    "vendor": "UBUNTU"
                }, 
                {
                    "url": "http://seclists.org/oss-sec/2013/q2/447", 
                    "vendor": "MLIST"
                }, 
                {
                    "url": "http://lists.opensuse.org/opensuse-updates/2013-06/msg00180.html", 
                    "vendor": "SUSE"
                }, 
                {
                    "url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=710597", 
                    "vendor": "MISC"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "2.9", 
                    "access complexity": "medium", 
                    "confidentiality impact": "none", 
                    "authentication": "none", 
                    "exploit": "8.6", 
                    "base": "4.3", 
                    "integrity impact": "none", 
                    "availability impact": "partial", 
                    "access vector": "network"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2013-2132"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:18100", 
                "title": "DSA-2705-1 pymongo - denial of service", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:18100"
            }, 
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.mitre.oval:def:21215", 
                "title": "USN-1897-1 -- pymongo vulnerability", 
                "class": "patch", 
                "id": "oval:org.mitre.oval:def:21215"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "Debian Security Advisory DSA 2705-1 (pymongo - denial of service)", 
                "file": "deb_2705.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "892705"
            }, 
            {
                "name": "Ubuntu Update for pymongo USN-1897-1", 
                "file": "gb_ubuntu_USN_1897_1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "841500"
            }
        ], 
        "Nessus": [
            {
                "name": "Debian DSA-2705-1 : pymongo - denial of service", 
                "file": "debian_DSA-2705.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "66851"
            }, 
            {
                "name": "openSUSE Security Update : python-pymongo / python3-pymongo (openSUSE-SU-2013:1064-1)", 
                "file": "openSUSE-2013-522.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "75053"
            }, 
            {
                "name": "RHEL 6 : MRG (RHSA-2013:1170)", 
                "file": "redhat-RHSA-2013-1170.nasl", 
                "family": "Red Hat Local Security Checks", 
                "id": "76662"
            }, 
            {
                "name": "Ubuntu 12.04 LTS / 12.10 / 13.04 : pymongo vulnerability (USN-1897-1)", 
                "file": "ubuntu_USN-1897-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "67188"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [
            {
                "url": "https://www.suse.com/security/cve/CVE-2013-2132.html", 
                "id": "openSUSE-SU-2013:1064"
            }
        ], 
        "Redhat": [], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [
            {
                "url": "http://www.ubuntu.com/usn/USN-1897-1", 
                "id": "USN-1897-1"
            }
        ], 
        "Debian": [
            {
                "url": "https://security-tracker.debian.org/tracker/DSA-2705", 
                "id": "DSA-2705"
            }
        ], 
        "Vmware": []
    }
}