{
    "Information": {
        "Category": [
            {
                "url": "https://cwe.mitre.org/data/definitions/668.html", 
                "id": "CWE-668", 
                "title": "Exposure of Resource to Wrong Sphere"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/199.html", 
                "id": "CWE-199", 
                "title": "Information Management Errors"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/717.html", 
                "id": "CWE-717", 
                "title": "OWASP Top Ten 2007 Category A6 - Information Leakage and Improper Error Handling"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/840.html", 
                "id": "CWE-840", 
                "title": "Business Logic Errors"
            }, 
            {
                "url": "https://cwe.mitre.org/data/definitions/963.html", 
                "id": "CWE-963", 
                "title": "SFP Secondary Cluster: Exposed Data"
            }
        ], 
        "CAPEC": [
            {
                "url": "https://capec.mitre.org/data/definitions/13.html", 
                "id": 13
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/169.html", 
                "id": 169
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/22.html", 
                "id": 22
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/472.html", 
                "id": 472
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/59.html", 
                "id": 59
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/60.html", 
                "id": 60
            }, 
            {
                "url": "https://capec.mitre.org/data/definitions/79.html", 
                "id": 79
            }
        ], 
        "CVE": [
            {
                "url": "http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2015-8213", 
                "published": "2015-12-07T15:59:17.613-05:00", 
                "id": "CVE-2015-8213", 
                "modified": "2015-12-08T15:43:32.050-05:00", 
                "summary": "The get_format function in utils/formats.py in Django before 1.7.x before 1.7.11, 1.8.x before 1.8.7, and 1.9.x before 1.9rc2 might allow remote attackers to obtain sensitive application secrets via a settings key in place of a date/time format setting, as demonstrated by SECRET_KEY."
            }
        ], 
        "CWE": [
            {
                "url": "https://cwe.mitre.org/data/definitions/200.html", 
                "id": "CWE-200", 
                "title": "Information Exposure"
            }
        ], 
        "CPE": [
            {
                "id": "cpe:/a:djangoproject:django:1.8.1"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.8.2"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.7.10"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.8.0"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.8.5"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.8.6"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.8.3"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.8.4"
            }, 
            {
                "id": "cpe:/a:djangoproject:django:1.9.0:rc1"
            }
        ]
    }, 
    "References": {
        "SCIP": [
            {
                "url": "http://www.scip.ch/?vuldb.79333", 
                "id": 79333
            }
        ], 
        "IAVM": [], 
        "BID": [], 
        "OSVDB": [], 
        "Other": {
            "References": [
                {
                    "url": "https://www.djangoproject.com/weblog/2015/nov/24/security-releases-issued/", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "https://github.com/django/django/commit/316bc3fc9437c5960c24baceb93c73f1939711e4", 
                    "vendor": "CONFIRM"
                }, 
                {
                    "url": "http://www.ubuntu.com/usn/USN-2816-1", 
                    "vendor": "UBUNTU"
                }
            ]
        }, 
        "CertVN": []
    }, 
    "Risk": [
        {
            "CVSS v2": [
                {
                    "impact": "2.9", 
                    "access complexity": "low", 
                    "confidentiality impact": "partial", 
                    "authentication": "none", 
                    "exploit": "10.0", 
                    "base": "5.0", 
                    "integrity impact": "none", 
                    "availability impact": "none", 
                    "access vector": "network"
                }
            ], 
            "severity": "Moderate", 
            "Top alert": false, 
            "Top vulnerable": false
        }
    ], 
    "Rules": {
        "Suricata": [], 
        "Snort": []
    }, 
    "Exploits": {
        "Metasploit": [], 
        "ExploitDB": [], 
        "Elliot D2": [], 
        "Saint": []
    }, 
    "vFeed": {
        "Product": "vFeed - The Correlated Vulnerability and Threat Database", 
        "Contact": "@toolswatch", 
        "Author": "NJ OUCHN", 
        "URL": "https://github.com/toolswatch/vFeed", 
        "Version": "0.6.5", 
        "id": "VFD-2015-8213"
    }, 
    "Scanners": {
        "Oval": [
            {
                "url": "http://oval.mitre.org/repository/data/getDef?id=oval:org.cisecurity:def:277", 
                "title": "DSA-3404-1 python-django -- security update", 
                "class": "patch", 
                "id": "oval:org.cisecurity:def:277"
            }
        ], 
        "Nmap": [], 
        "OpenVas": [
            {
                "name": "Debian Security Advisory DSA 3404-1 (python-django - security update)", 
                "file": "deb_3404.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "703404"
            }
        ], 
        "Nessus": [
            {
                "name": "Debian DLA-349-1 : python-django security update", 
                "file": "debian_DLA-349.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "87070"
            }, 
            {
                "name": "Debian DSA-3404-1 : python-django - security update", 
                "file": "debian_DSA-3404.nasl", 
                "family": "Debian Local Security Checks", 
                "id": "87077"
            }, 
            {
                "name": "Fedora 22 : python-django-1.8.7-1.fc22 (2015-323274d412)", 
                "file": "fedora_2015-323274d412.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "89201"
            }, 
            {
                "name": "Fedora 23 : python-django-1.8.7-1.fc23 (2015-a8c8f60fbd)", 
                "file": "fedora_2015-a8c8f60fbd.nasl", 
                "family": "Fedora Local Security Checks", 
                "id": "89358"
            }, 
            {
                "name": "FreeBSD : django -- information leak vulnerability (11c52bc6-97aa-11e5-b8df-14dae9d210b8)", 
                "file": "freebsd_pkg_11c52bc697aa11e5b8df14dae9d210b8.nasl", 
                "family": "FreeBSD Local Security Checks", 
                "id": "87114"
            }, 
            {
                "name": "openSUSE Security Update : python-django (openSUSE-2015-860)", 
                "file": "openSUSE-2015-860.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "87438"
            }, 
            {
                "name": "openSUSE Security Update : python-Django (openSUSE-2015-862)", 
                "file": "openSUSE-2015-862.nasl", 
                "family": "SuSE Local Security Checks", 
                "id": "87439"
            }, 
            {
                "name": "Ubuntu 12.04 LTS / 14.04 / 15.04 / 15.10 : python-django vulnerability (USN-2816-1)", 
                "file": "ubuntu_USN-2816-1.nasl", 
                "family": "Ubuntu Local Security Checks", 
                "id": "87065"
            }
        ]
    }, 
    "Patches": {
        "Fedora": [], 
        "HP": [], 
        "Microsoft KB": [], 
        "Mandriva": [], 
        "Cisco": [], 
        "IBM AIX Apar": [], 
        "Suse": [], 
        "Redhat": [], 
        "Gentoo": [], 
        "Microsoft Bulletins": [], 
        "Ubuntu": [
            {
                "url": "http://www.ubuntu.com/usn/USN-2816-1", 
                "id": "USN-2816-1"
            }
        ], 
        "Debian": [], 
        "Vmware": []
    }
}